apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: artifact-registry
  labels:
    app: docker-registry
    tier: registry
data:
  REGISTRY_HTTP_ADDR: 0.0.0.0:5000
  REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
