apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
  labels:
    app: docker-registry
    tier: registry
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/registry
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  namespace: artifact-registry
  labels:
    app: docker-registry
    tier: registry
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: docker-registry
      tier: registry
