apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: artifact-registry
  labels:
    app: docker-registry
    tier: registry
spec:
  type: NodePort
  selector:
    app: docker-registry
    tier: registry
  ports:
    - name: registry
      port: 5000
      targetPort: 5000
      nodePort: 30500
