apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: backend
type: Opaque
stringData:
  MONGO_URI: "mongodb://admin:admin123@mongo.database.svc.cluster.local:27017/hotelapp?authSource=admin"
