apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: hotel-backend
  labels:
    app: backend
    tier: backend
type: Opaque
stringData:
  JWT_SECRET: change-me-in-production
  API_KEY: lh-practice-api-key
