apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: hotel-backend
  labels:
    app: backend
    tier: backend

spec:
  replicas: 5
  selector:
    matchLabels:
      app: backend
      tier: backend
  
  template:
    metadata:
      labels:
        app: backend
        tier: backend

      annotations:
        # Use 'hashicorp'
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "hotel-backend"
        vault.hashicorp.com/agent-inject-secret-mongo-uri: "secret/data/hotel/backend"
        vault.hashicorp.com/agent-inject-template-mongo-uri: |     
          {{- with secret "secret/data/hotel/backend" -}}
          {{ .Data.data.MONGO_URI }}
          {{- end }}

    spec:
      serviceAccountName: backend

      containers:
        - name: backend
          image: host.docker.internal:8082/backend:1407997848c4cfcde79476518d5e35bc3ce544ea

          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
              name: http

          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret

          readinessProbe:
            httpGet:
              path: /hotels
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10
          
          livenessProbe:
            httpGet:
              path: /hotels
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 20
          
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      
      imagePullSecrets:
        - name: regcred
