apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: hotel-frontend
  labels:
    app: frontend
    tier: frontend
data:
  BACKEND_URL: http://backend.hotel-backend.svc.cluster.local:3000
  VITE_BACKEND_URL: http://backend.hotel-backend.svc.cluster.local:3000
