apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/gswack/infra-repo
    targetRevision: main
    path: kubernetes/nexus

  destination:
    server: https://kubernetes.default.svc
    namespace: nexus