apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      securityContext:
        fsGroup: 200
      containers:
        - name: nexus
          image: sonatype/nexus3:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: nexus-ui
            - containerPort: 8082
              # name: nexus-ui
              name: docker-registry
          env:
            - name: INSTALL4J_ADD_VM_PARAMS
              value: "-Xms512m -Xmx512m -XX:MaxDirectMemorySize=512m"
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 90
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 5
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-data-pvc